services:
  - type: web
    name: crosscourse-assignment-php-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
